receivers:
    otlp:
      protocols:
        http:
          endpoint: 0.0.0.0:4317          

exporters:
  signalfx:
    realm: "${SPLUNK_REALM}"
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # api_url: "https://api.us1.signalfx.com"
    # ingest_url: "https://ingest.us1.signalfx.com"
    # Use instead when sending to gateway
    #api_url: http://${SPLUNK_GATEWAY_URL}:6060
    #ingest_url: http://${SPLUNK_GATEWAY_URL}:9943
    sync_host_metadata: false
    correlation: null

  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    # access_token_passthrough: true
    endpoint: "${SPLUNK_TRACE_URL}"  
    max_connections: 100
    num_workers: 8
    log_detailed_response: true

processors:
    batch:

extensions:
    health_check:
      endpoint: 0.0.0.0:13133
    pprof:
      endpoint: :1888
    zpages:
      endpoint: :55679

service:
    extensions: [pprof, zpages, health_check]
    pipelines:
      traces:
        receivers: [otlp]
        # receivers: [jaeger]        
        processors: [batch]
        # exporters: [signalfx, splunk_hec/traces, debug,sapm]
        exporters: [signalfx, sapm]
